In [1]:
import torch
import torch.nn
import gensim

/home/piai/anaconda3/envs/course/lib/python3.8/site-packages/gensim/similarities/__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [2]:
vocab = {
    '한국': 0,
    '북한': 1,
    '인공지능': 2,
    '대한민국': 3,
    '실습': 4
}

In [3]:
model = gensim.models.Word2Vec.load('newskor.model')

In [6]:
## vocab에 등록된 단어의 사전훈련 벡터 결과 출력 ##
model.wv['한국']
#print(len(model.wv['한국']))

array([-3.40771258e-01,  5.86871326e-01,  1.48174763e-01,  7.55309984e-02,
        2.80051623e-02, -3.29737902e-01,  2.82022148e-01,  4.34874058e-01,
        4.70132902e-02,  2.15171650e-01,  2.39689067e-01, -2.92732924e-01,
       -2.55399585e-01, -3.40860970e-02,  2.49378029e-02, -2.06564948e-01,
        4.05827940e-01, -1.32219950e-02, -7.67219141e-02, -1.27523661e-01,
       -7.80721754e-02,  1.04432628e-01,  2.91436523e-01,  1.06755883e-01,
       -4.02816720e-02,  4.57676547e-03,  9.44675580e-02, -6.16809912e-02,
       -2.33795762e-01, -1.90607198e-02, -4.59343046e-02, -3.74667704e-01,
        4.30130005e-01, -9.34120715e-02, -7.44743571e-02,  4.15772557e-01,
        2.65666306e-01,  6.67319372e-02, -1.67954132e-01, -2.51299478e-02,
        5.63483639e-03, -1.88397303e-01, -6.40374571e-02,  1.31152689e-01,
        8.07553604e-02, -1.37501344e-01, -1.76888227e-01,  2.62515191e-02,
       -3.39076146e-02,  1.36987016e-01, -6.33930936e-02,  6.23895600e-02,
       -8.52504149e-02,  

In [19]:
## previous version ##
#dim=10
#emb_mtx = torch.nn.Embedding(len(vocab), dim)

## new version ##
#dim=model.wv.vector_size 
#weights=[[weight for 청년], [weight for AI], [weight for BIGDATA], ...]
#emb_mtx = torch.nn.Embedding.from_pretrained(weights)


In [7]:
def get_weights(vocab, embd):
    weights = []
    for word in vocab.keys():
        w = embd.wv[word]
        weights.append(w)
    return torch.tensor(weights)

In [8]:
dim=model.wv.vector_size
weights = get_weights(vocab, model)
emb_mtx = torch.nn.Embedding.from_pretrained(weights)

In [9]:
## Practice 1 ##

# print word embedding of '한국'
idx = torch.tensor([vocab['한국']], dtype=torch.long) # make index tensor for '한국'
print(idx)
emb_mtx(idx) # feed index tensor to emb_mtx

tensor([0])


tensor([[-3.4077e-01,  5.8687e-01,  1.4817e-01,  7.5531e-02,  2.8005e-02,
         -3.2974e-01,  2.8202e-01,  4.3487e-01,  4.7013e-02,  2.1517e-01,
          2.3969e-01, -2.9273e-01, -2.5540e-01, -3.4086e-02,  2.4938e-02,
         -2.0656e-01,  4.0583e-01, -1.3222e-02, -7.6722e-02, -1.2752e-01,
         -7.8072e-02,  1.0443e-01,  2.9144e-01,  1.0676e-01, -4.0282e-02,
          4.5768e-03,  9.4468e-02, -6.1681e-02, -2.3380e-01, -1.9061e-02,
         -4.5934e-02, -3.7467e-01,  4.3013e-01, -9.3412e-02, -7.4474e-02,
          4.1577e-01,  2.6567e-01,  6.6732e-02, -1.6795e-01, -2.5130e-02,
          5.6348e-03, -1.8840e-01, -6.4037e-02,  1.3115e-01,  8.0755e-02,
         -1.3750e-01, -1.7689e-01,  2.6252e-02, -3.3908e-02,  1.3699e-01,
         -6.3393e-02,  6.2390e-02, -8.5250e-02,  3.1169e-01,  1.3142e-01,
          1.0782e-01, -8.5697e-02,  2.2210e-01, -2.5530e-02, -1.3544e-02,
         -2.2714e-01, -2.4158e-01,  6.2465e-02,  5.4535e-02,  1.4425e-01,
          6.1582e-02, -3.0912e-02,  2.